/*
	Task#4: Write a program in openMP C to find number of permutation words created by any
	given string. Example “Happy” is 5 letter word and can generate 5! Words. Now each
	combination will be generated by different thread and calculate the time individually.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <omp.h>

int fact(int n)
{
	if(n > 0) return n*fact(n-1);
	else return 1;
}

int main(int argc, char* argv[], char* envp[])
{
	char* val = "Happy";
	int n = strlen(val);
	int perm = fact(n);						//Calculating all total number of permutations
	char PossiblePerms[perm][n+1];					//Creating an array to store all possible permutations
	
	double t1;
	#pragma omp parallel num_threads(8)				//Start of parallel region
	{
		#pragma single
		{
			t1 = omp_get_wtime();
		}
		#pragma omp for
		for(int i = 0; i < perm; i++)				
		{
			char temp[n+1];
			strcpy(temp, val);
			for(int j = 0; j < n; j++)			//Swapping elements to get all possible permutations{also known as Next Permutation Algorithm}
			{
				int k = i / fact(n-1-j) % (n-j);
				char swap = temp[j];
				temp[j] = temp[j+k];
				temp[j+k] = swap;
			}
			strcpy(PossiblePerms[i], temp);			//Storing a permutation in the array
		}
	}
	double t2 = omp_get_wtime();
	
	for(int i = 0; i < perm; i++)
		printf("%s\n", PossiblePerms[i]);
	printf("Time taken to calculate all possible permutations: %f\n",t2-t1);
}
